// console.log("Hello JS");
// // var a=12;
// const a=12;
// if(a>10){
//    let b=23;
//    a=40;
//     console.log("a="+a);
// }
// console.log("hi, a="+a);
// console.log("hi, a="+b);
// function fun(a,b){
//     console.log("hi");
//     return a+b;
// }
// let data=fun();
// console.log(data);
// function fun(a,b,c=10){
//     console.log("hi");
//     return a+b;
// }
// let data=fun(17,5);
// console.log(data);
// function fun(a,b,c=10){
//     console.log("hi");
//     return a+b+c;
// }
// let data=fun(17,5);
// console.log(data);
// function cCompiler(){
//     return "C Compiler";
// }
// function javaCompiler(){
//      return "Java Compiler";
// }
// function selectlanguage(clbk){
//     return "You have Selected " +clbk();
// }
// const result=selectlanguage(cCompiler);
// console.log(result);
// function selectlanguage(language="no compiler selected") {
//     let data;
    
//     if (language == 'C') {
//         function cCompiler() {
//             return "C Compiler";
//         }
//         data = cCompiler;
//     }
    
//     if (language == 'Java') {
//         function javaCompiler() {
//             return "Java Compiler";
//         }
//         data = javaCompiler;
//     }
    
//     return data;
// }

// const result = selectlanguage("C");
// console.log(result());  
// function selectlanguage(language="no compiler selected") {
//     let data=language;
    
//     if (language == 'C') {
//         function cCompiler() {
//             return "C Compiler";
//         }
//         data = cCompiler;
//     }
    
//     if (language == 'Java') {
//         function javaCompiler() {
//             return "Java Compiler";
//         }
//         data = javaCompiler;
//     }
    
//     return data;
// }

// const result = selectlanguage("Java");
// console.log(result());  
// console.dir(document);
// const div=document.getElementsByClassName("parent");
// console.dir(div);
// div[0].innerHTML="<h2 style=color:purple>ABES ENGINEERING COLLEGE </h2>";
// const h1=document.createElement("h1");
// h1.innerText="this is generated by DOM";
// h1.style.backgroundColor="pink";
// console.log(h1);
// div[0].appendChild(h1);
// const img=document.createElement('img');
// img.src='./hotel.jpg';
// img.setAttribute("height","200");
// console.log(img);
// div[0].appendChild(img);
// const btn=document.getElementById("btn");
// const disp=document.getElementById("disp");
// console.dir(disp);
// function getData(){
//     console.log("GetData called");
//     disp.innerHTML="<h2>Hello, You have called GetData</h2>";
// }
// btn.addEventListener("click",getData);
const promise=new Promise((resolve,reject)=>{
    let a=12;
    if(a>10){
        resolve({name:"Rahul",branch:"AIMLCSE"});
    }
    else{
        reject("Rejected");
    }
});
promise.then((msg)=>console.log(msg)).catch(error=>console.log(error));
